FROM openjdk:8

WORKDIR /roulette/bin

ENV PORT 6000

COPY /target/classes /roulette/bin/classes
COPY /target/dependency /roulette/bin/dependency

CMD ["java","-cp","./classes:./dependency/*","com.masiv.casinoapi.App"]